services:
  - type: worker
    name: discord-stock-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_new.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: INFO
